FROM node:22

RUN npm install -g pnpm

# COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# RUN apt-get update && apt-get install -y vim git curl

ARG UID
ARG GID

RUN groupadd -g ${GID} devuser && \
    useradd -u ${UID} -g ${GID} -m -s /bin/bash devuser

USER devuser

WORKDIR /workspace

# RUN uv python install 3.12

# RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash

# RUN nvm install 22
# RUN npm install -g pnpm