import type { Metadata } from "next";
import "./globals.css";
import NavigationMenuDemo from "@/components/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="border-b">
          <div className="container ml-4 py-4">
            <NavigationMenuDemo />
          </div>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
